[package]
name = "librespot-metadata"
version = "0.1.2"
authors = ["Paul Lietar <paul@lietar.net>"]
description="The metadata logic for librespot"
license="MIT"
edition = "2018"

[dependencies]
byteorder = "1.3"
futures = "0.1"
linear-map = "1.2"
protobuf = "~2.14.0"
log = "0.4"

[dependencies.librespot-core]
path = "../core"
version = "0.1.2"
[dependencies.librespot-protocol]
path = "../protocol"
version = "0.1.2"
